### ISSUE TITLE
generate_blpolicy_oemvars: No such file or directory

### ISSUE THREAD

**Issue by strassek** [projectceladon/device-intel-build#10]
Celadon master is failing to build 'flashfiles' target on Ubuntu 16.04.5 with this error:
```
[  0% 626/86312] build out/target/product/celadon/bootloader_policy-oemvars.txt
FAILED: out/target/product/celadon/bootloader_policy-oemvars.txt 
/bin/bash -c "device/intel/build/generate_blpolicy_oemvars -K device/intel/build/testkeys/odm 		-O device/intel/build/testkeys/OAK.x509.pem -B 0x0 		out/target/product/celadon/bootloader_policy-oemvars.txt"
Traceback (most recent call last):
  File "device/intel/build/generate_blpolicy_oemvars", line 261, in <module>
    main(sys.argv[1:])
  File "device/intel/build/generate_blpolicy_oemvars", line 229, in main
    password, guid, "OAK", m.digest())
  File "device/intel/build/generate_blpolicy_oemvars", line 144, in get_auth_data
    name, payload_fname, auth_fname], None)
  File "device/intel/build/generate_blpolicy_oemvars", line 73, in run
    p = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by strassek** [comment]
Turns out 'efitools' is now a build dependency:
https://lists.01.org/pipermail/celadon/2018-August/001302.html

Leaving this bug open until the docs have been updated.
